# Generated by Django 6.0.2 on 2026-02-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('user', '0002_alter_libraryuser_managers_and_more'), ('user', '0003_alter_libraryuser_password'), ('user', '0004_alter_libraryuser_password'), ('user', '0005_alter_libraryuser_password')]

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='libraryuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='password',
            field=models.CharField(max_length=350),
        ),
    ]
