# Generated by Django 6.0.2 on 2026-02-19 06:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_libraryuser_managers_and_more_squashed_0005_alter_libraryuser_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='libraryuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
