# Generated by Django 6.0.2 on 2026-02-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_libraryuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='libraryuser',
            managers=[
            ],
        ),
    ]
