# Generated by Django 6.0.2 on 2026-02-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_libraryuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryuser',
            options={'permissions': (('can_add_book', 'To let sellers add new products'), ('can_buy_book', 'To let only normal users buy books'))},
        ),
    ]
