# Generated by Django 6.0.2 on 2026-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_libraryuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryuser',
            options={'permissions': [('can_add_book', 'To let sellers add new products'), ('can_buy_book', 'To let only normal users buy books')]},
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='can_add_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='can_buy_book',
            field=models.BooleanField(default=False),
        ),
    ]
