# Generated by Django 6.0.2 on 2026-02-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_libraryuser_options_libraryuser_can_add_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='can_add_book',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='can_buy_book',
        ),
    ]
